name: GitHub Pac-Man Game

on:
  schedule:
    - cron: '0 0 * * *' # Каждый день в полночь UTC
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      # Шаг 1: Клонируем репозиторий
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Шаг 2: Генерация Pac-Man SVG
      - name: Generate GitHub Contributions Pac-Man Animation
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: ${{ github.repository_owner }}
      
      # Шаг 3: Переместим SVG в dist (если нужно)
      - name: Organize output into dist folder
        run: |
          mkdir -p dist
          if [ -f pacman-contribution-graph.svg ]; then
            cp pacman-contribution-graph.svg dist/github-pacman.svg
          fi
          if [ -f pacman-contribution-graph-dark.svg ]; then
            cp pacman-contribution-graph-dark.svg dist/github-pacman-dark.svg
          fi

      # Шаг 4: Публикация на ветку output
      - name: Deploy to Output Branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: output
          commit_message: 'Update pacman animation [skip ci]'
