name: GitHub Pac-Man Game

on:
  # Schedule the workflow to run daily at midnight UTC
  schedule:
    - cron: "0 0 * * *"

  # Allow manual triggering of the workflow
  workflow_dispatch:

  # Trigger the workflow on pushes to the main branch
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Generate the Pac-Man graph
      - name: Generate GitHub Contributions Pac-Man Graph
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: ${{ github.repository_owner }}

      # Step 3: Move output files into dist directory
      - name: Organize Output Files
        run: |
          mkdir -p dist
          if [ -f pacman-contribution-graph.svg ]; then
            cp pacman-contribution-graph.svg dist/github-pacman.svg
          fi
          if [ -f pacman-contribution-graph-dark.svg ]; then
            cp pacman-contribution-graph-dark.svg dist/github-pacman-dark.svg
          fi

      # Step 4: Deploy to output branch
      - name: Deploy to Output Branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: output
          commit_message: "Update pacman animation [skip ci]"
