name: Generate Pac-Man Game

on:
  schedule:
    - cron: "0 2 * * *"  # Каждый день в 2:00 ночи UTC
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Clean output directory
        run: rm -rf dist && mkdir -p dist

      - name: Generate pacman-contribution-graph.svg
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: ${{ github.repository_owner }}
        continue-on-error: true

      - name: Check SVG exists
        run: |
          if [ ! -f dist/pacman-contribution-graph.svg ]; then
            echo "SVG not found. Exiting..."
            exit 1
          fi

      - name: Push pacman-contribution-graph.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
