name: Update Trophies

on:
  schedule:
    - cron: '0 0 * * *' # Запускается каждый день
  workflow_dispatch: # Кнопка для ручного запуска

jobs:
  update-trophies:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download Trophies SVG
        run: |
          mkdir -p profile
          curl -o profile/trophies.svg "https://github-profile-trophy.vercel.app/?username=AlexKim71&theme=radical&column=7&no-frame=true&no-bg=true&margin-w=15&margin-h=15"

      - name: Commit and push changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add profile/trophies.svg
          git commit -m "Update GitHub Trophies" || exit 0
          git push
